{application,boxsolver_core,
             [{description,"boxsolver core"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{boxsolver_core_app,[]}},
              {env,[]},
              {modules,[boxsolver_core,boxsolver_core_app,
                        boxsolver_core_server,boxsolver_core_sup,
                        boxsolver_json,boxsolver_riak_config]}]}.
